version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: dbai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: book_store
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "3306:3306"

  dbgate:
    image: dbgate/dbgate
    environment:
      CONNECTIONS: con1,con2
      LABEL_con1: PostgreSQL
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: postgres
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
      LABEL_con2: MySQL
      SERVER_con2: mysql
      USER_con2: mysqluser
      PASSWORD_con2: mysqlpassword
      PORT_con2: 3306
      ENGINE_con2: mysql@dbgate-plugin-mysql
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mysql

volumes:
  postgres_data:
  mysql_data:
